namespace IPCU.Services
{
    using QuestPDF.Fluent;
    using QuestPDF.Helpers;
    using QuestPDF.Infrastructure;
    using IPCU.Models;
    using System.IO;

    public class TrainingEvaluationPdfService
    {
        public static byte[] GeneratePdf(TrainingEvaluation training)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.Header().Text("Training Evaluation Report").Bold().FontSize(20).AlignCenter();

                    page.Content().Column(col =>
                    {
                        col.Item().Text($"Title: {training.Title}");
                        col.Item().Text($"Venue: {training.Venue}");
                        col.Item().Text($"Date: {training.DateOfTraining:dd MMM yyyy}");
                        col.Item().Text($"Methodology: {training.TrainingMethodology}");
                        col.Item().Text($"Category: {training.ProfessionalCategory}");
                        col.Item().Text($"Participants: {training.TotalParticipantsMale} Male, {training.TotalParticipantsFemale} Female");
                        col.Item().Text($"Post-Test Grade: {training.PostTestEvaluationGrade}");
                      //  col.Item().Spacing(10);

                        col.Item().Text("Ratings").Bold().FontSize(16);
                        col.Item().Text($"Flow Followed: {training.FlowFollowed}");
                        col.Item().Text($"Rules Established: {training.RulesEstablished}");
                        col.Item().Text($"Initiate Discussion: {training.InitiateDiscussion}");
                        col.Item().Text($"Technical Capability: {training.TechnicalCapability}");

                      //  col.Item().Spacing(10);
                        col.Item().Text("Suggestions for Improvement:").Bold();
                        col.Item().Text(training.SuggestionsForImprovement ?? "N/A");
                    });

                    page.Footer().Text("Generated by IPCU System").FontSize(10).AlignCenter();
                });
            }).GeneratePdf();
        }
    }
}