using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IPCU.Migrations
{
    /// <inheritdoc />
    public partial class ENVI : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "EnvironmentalzControl",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Fname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Lname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Mname = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EmployeeId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    AreaOrUnit = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DateAndTimeOfMonitoring = table.Column<DateTime>(type: "datetime2", nullable: false),
                    AssessedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_FloorsWallsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_FloorsWallsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_FloorsWallsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_FloorsWallsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_FloorsWallsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_CurtainsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_CurtainsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_CurtainsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_CurtainsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_CurtainsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_SinkClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_SinkClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_SinkClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_SinkClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_SinkClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_SoapDispenser_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_SoapDispenser_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_SoapDispenser_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_SoapDispenser_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_SoapDispenser_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_AlcoholSanitizers_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_AlcoholSanitizers_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_AlcoholSanitizers_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_AlcoholSanitizers_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_AlcoholSanitizers_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_PPEAvailable_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_PPEAvailable_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_PPEAvailable_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_PPEAvailable_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_PPEAvailable_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_NoSuppliesUnderSinks_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_NoSuppliesUnderSinks_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_NoSuppliesUnderSinks_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_NoSuppliesUnderSinks_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_NoSuppliesUnderSinks_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_NoFoodInCareAreas_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_NoFoodInCareAreas_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PatientExamRoom_NoFoodInCareAreas_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PatientExamRoom_NoFoodInCareAreas_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PatientExamRoom_NoFoodInCareAreas_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_ChartsStored_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_ChartsStored_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_ChartsStored_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_ChartsStored_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_ChartsStored_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_NoFoodOrDrinks_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_NoFoodOrDrinks_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_NoFoodOrDrinks_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_NoFoodOrDrinks_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_NoFoodOrDrinks_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_FansClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_FansClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_FansClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_FansClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_FansClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_ACClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_ACClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_ACClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_ACClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_ACClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_ExhaustFansClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_ExhaustFansClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_ExhaustFansClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_ExhaustFansClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_ExhaustFansClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_CeilingClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_CeilingClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_CeilingClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_CeilingClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_CeilingClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_WallsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_WallsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_WallsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_WallsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_WallsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_CountersClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_CountersClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_CountersClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_CountersClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_CountersClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_FloorsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_FloorsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_FloorsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_FloorsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_FloorsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_DoorsWindowsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_DoorsWindowsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_DoorsWindowsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_DoorsWindowsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_DoorsWindowsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_CleanBathroom_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_CleanBathroom_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WorkArea_CleanBathroom_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkArea_CleanBathroom_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WorkArea_CleanBathroom_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hallway_FloorsWallsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Hallway_FloorsWallsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Hallway_FloorsWallsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hallway_FloorsWallsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Hallway_FloorsWallsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hallway_NoObstruction_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Hallway_NoObstruction_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Hallway_NoObstruction_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hallway_NoObstruction_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Hallway_NoObstruction_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaitingArea_FurnitureClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WaitingArea_FurnitureClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WaitingArea_FurnitureClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaitingArea_FurnitureClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WaitingArea_FurnitureClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaitingArea_TrashDisposed_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WaitingArea_TrashDisposed_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WaitingArea_TrashDisposed_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaitingArea_TrashDisposed_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WaitingArea_TrashDisposed_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaitingArea_FoodInDesignatedArea_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WaitingArea_FoodInDesignatedArea_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WaitingArea_FoodInDesignatedArea_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaitingArea_FoodInDesignatedArea_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WaitingArea_FoodInDesignatedArea_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Equipment_StorageClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Equipment_StorageClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Equipment_StorageClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Equipment_StorageClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Equipment_StorageClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_CleanSoiledSeparation_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_CleanSoiledSeparation_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_CleanSoiledSeparation_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_CleanSoiledSeparation_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_CleanSoiledSeparation_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_FloorsWallsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_FloorsWallsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_FloorsWallsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_FloorsWallsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_FloorsWallsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_NoSuppliesOnFloor_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_NoSuppliesOnFloor_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_NoSuppliesOnFloor_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_NoSuppliesOnFloor_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_NoSuppliesOnFloor_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_SuppliesFromCeiling_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_SuppliesFromCeiling_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_SuppliesFromCeiling_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_SuppliesFromCeiling_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_SuppliesFromCeiling_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_NoSuppliesUnderSink_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_NoSuppliesUnderSink_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_NoSuppliesUnderSink_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_NoSuppliesUnderSink_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_NoSuppliesUnderSink_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_NoSuppliesInBathrooms_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_NoSuppliesInBathrooms_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_NoSuppliesInBathrooms_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_NoSuppliesInBathrooms_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_NoSuppliesInBathrooms_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_FIFOStocks_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_FIFOStocks_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_FIFOStocks_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_FIFOStocks_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_FIFOStocks_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_SuppliesNotExpired_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_SuppliesNotExpired_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_SuppliesNotExpired_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_SuppliesNotExpired_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_SuppliesNotExpired_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_SterileTraysClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_SterileTraysClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UtilityRoom_SterileTraysClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UtilityRoom_SterileTraysClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UtilityRoom_SterileTraysClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SoiledRoom_FloorsWallsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoiledRoom_FloorsWallsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoiledRoom_FloorsWallsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SoiledRoom_FloorsWallsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SoiledRoom_FloorsWallsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SoiledRoom_NoPatientSupplies_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoiledRoom_NoPatientSupplies_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoiledRoom_NoPatientSupplies_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SoiledRoom_NoPatientSupplies_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SoiledRoom_NoPatientSupplies_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SoiledRoom_LinenBagged_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoiledRoom_LinenBagged_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SoiledRoom_LinenBagged_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SoiledRoom_LinenBagged_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SoiledRoom_LinenBagged_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_ColorBinsAvailable_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_ColorBinsAvailable_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_ColorBinsAvailable_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_ColorBinsAvailable_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WasteMgmt_ColorBinsAvailable_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_ProperDisposal_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_ProperDisposal_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_ProperDisposal_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_ProperDisposal_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WasteMgmt_ProperDisposal_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_BinsNotOverfilled_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_BinsNotOverfilled_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_BinsNotOverfilled_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_BinsNotOverfilled_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WasteMgmt_BinsNotOverfilled_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_BinsClean_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_BinsClean_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_BinsClean_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_BinsClean_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WasteMgmt_BinsClean_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_SharpsLabeled_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_SharpsLabeled_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_SharpsLabeled_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_SharpsLabeled_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WasteMgmt_SharpsLabeled_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_SharpsNotOverfilled_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_SharpsNotOverfilled_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    WasteMgmt_SharpsNotOverfilled_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WasteMgmt_SharpsNotOverfilled_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    WasteMgmt_SharpsNotOverfilled_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Refrigerator_TempChecked_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Refrigerator_TempChecked_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Refrigerator_TempChecked_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Refrigerator_TempChecked_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Refrigerator_TempChecked_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Refrigerator_Dedicated_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Refrigerator_Dedicated_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Refrigerator_Dedicated_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Refrigerator_Dedicated_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Refrigerator_Dedicated_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_NoExpired_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_NoExpired_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_NoExpired_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_NoExpired_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Medications_NoExpired_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_VialsDated_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_VialsDated_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_VialsDated_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_VialsDated_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Medications_VialsDated_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_VaccinesStored_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_VaccinesStored_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_VaccinesStored_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_VaccinesStored_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Medications_VaccinesStored_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_NoLooseNeedles_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_NoLooseNeedles_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Medications_NoLooseNeedles_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medications_NoLooseNeedles_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Medications_NoLooseNeedles_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Misc_SpecimensLabeled_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Misc_SpecimensLabeled_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Misc_SpecimensLabeled_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Misc_SpecimensLabeled_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Misc_SpecimensLabeled_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Misc_StaffHygienePPE_Finding = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Misc_StaffHygienePPE_ActionDone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Misc_StaffHygienePPE_Remarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Misc_StaffHygienePPE_FuDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Misc_StaffHygienePPE_FuRemarks = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitAreaStaffSignature = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FollowUpDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EnvironmentalzControl", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EnvironmentalzControl");
        }
    }
}
